[package]
name = "yomu"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.13.1"
serde = {version ="1.0.228", features = ["derive"]}
serde_json = "1.0.149"
tokio = {version = "1", features = ["rt", "macros"]}
